import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'
import logo from '../assets/images/kastory-logo-04-bg-04.png'
import searchIcon from '../assets/icns/search_black_24dp.svg'
import InputBox from '../components/InputBox'
import Link from 'next/link'
import { Footer } from '../components/Footer'

export default function Home() {
  return (
	  <Layout>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/kastory-logo-04.png" />
			</Head>

			<main >
					<header>
					<div className={styles.logo}>

					{/* <img src="kastory-logo-04-bg-04.png" alt="kastory Logo" srcset="" className='logo'/> */}
					<Image src={logo} alt="kastory Logo" layout='fill'/>
					</div>
					<div className={styles.searchBox}>
					<InputBox inputType={'text'} placeholder={'search stories'} inputStyle={styles.inputBox}/>
					<Image src={searchIcon} alt="search icon"/>
					</div>
					</header>
				<section className={styles.main}>

				<p className={styles.description}>
				<h1>Short Stories and Novels</h1>
				<h3>Write your imagination</h3>
				<h1>Make yours known</h1>
				</p>
				</section>

				<aside className={styles.aside}>
				<ul>
					<li className={styles.navBtn}>
					<Link href={'/profile'}>
						<a>View</a>
					</Link>
					</li>
					<li className={styles.navBtn}>
					<Link href={'/login'} passHref>
						<a>Login</a>
					</Link>
					</li>
					<li className={styles.navBtn}>
					<Link href={'/register'}>
						<a>Register</a>
					</Link>
					</li>
					<li className={styles.navBtn}> 
					<Link href={'#'}>
						<a>Search</a>
					</Link>
					</li>
				</ul>
				</aside>
			</main>

			<Footer/>
			<style jsx>
				{`
				#grid{
					color: red;
				}
				a{
					text-decoration:none;
				}
				`}
			</style>
		</Layout>
	);
}
